# Generated by Django 5.1.4 on 2024-12-31 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceInfoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the service info category, e.g., Privacy, Security, AI.",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Info Category",
                "verbose_name_plural": "Service Info Categories",
            },
        ),
        migrations.AddField(
            model_name="serviceinfo",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category of service info.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_infos",
                to="registry.serviceinfocategory",
            ),
        ),
    ]
