# Generated by Django 5.1.4 on 2025-01-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_serviceinfocategory_serviceinfo_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceinfocategory",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Order"
            ),
        ),
    ]
