# Generated by Django 5.1.4 on 2025-01-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_service_icon_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
