# Generated by Django 5.1.4 on 2025-01-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0004_alter_serviceinfocategory_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serviceinfocategory",
            options={
                "ordering": ["order"],
                "verbose_name": "Service Info Category",
                "verbose_name_plural": "Service Info Categories",
            },
        ),
    ]
