# Generated by Django 5.1.4 on 2025-01-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0005_alter_serviceinfocategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average rating of the service.",
                max_digits=3,
                null=True,
            ),
        ),
    ]
