# Generated by Django 5.1.4 on 2025-01-31 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0004_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='Name of the action.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this action does.', null=True)),
                ('handler', models.CharField(blank=True, help_text='Path to a custom handler for this action. Example: actions.handlers.nice_service.delete_comments', max_length=255, null=True)),
                ('service', models.ForeignKey(help_text='The service this action is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='registry.service')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
    ]
