# Generated by Django 5.1.4 on 2025-01-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='The requested URL path.', max_length=255, unique=True, verbose_name='Path')),
                ('user_count', models.PositiveIntegerField(default=0, help_text='Number of requests by users.', verbose_name='User Count')),
                ('bot_count', models.PositiveIntegerField(default=0, help_text='Number of requests by bots.', verbose_name='Bot Count')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
                'ordering': ['path'],
            },
        ),
    ]
